<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>data_recorder</name>
  <version>0.1.0</version>
  <description>Qt/QML UI prototype for ROS 2 data recording workflows.</description>
  <maintainer email="nros@example.com">nros</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>ament_index_cpp</depend>
  <depend>yaml-cpp</depend>
  <depend>rosbag2_cpp</depend>
  <depend>rosbag2_storage</depend>
  <depend>rosbag2_transport</depend>
  <depend>sensor_msgs</depend>
  <depend>libavcodec-dev</depend>
  <depend>libavformat-dev</depend>
  <depend>libavutil-dev</depend>
  <depend>libswscale-dev</depend>
  <exec_depend>ros-humble-rosbag2-storage-mcap</exec_depend>
  <depend>qt6-base-dev</depend>
  <depend>qt6-declarative-dev</depend>
  <exec_depend>qml6-module-qtcharts</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
